version: '2'

services:

  dms:
    image: andrglo/everest:12.0.0
    hostname: json-schema-entity
    command: tail -f /dev/null
    working_dir: /root/json-schema-entity
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/json-schema-entity
    environment:
      - NODE_ENV=test
      - MSSQL_PASSWORD=Juriti01
      - MSSQL_USER=sa
      - NPM_TOKEN=$NPM_TOKEN
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU12
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Juriti01
      - MSSQL_PID=Express
      - MSSQL_COLLATION=Latin1_General_CI_AI
    restart: always

  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always


