version: '2'

services:

  dms:
    image: andrglo/everest:10.2.1
    hostname: json-schema-entity
    command: tail -f /dev/null
    working_dir: /andrglo/json-schema-entity
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/andrglo/json-schema-entity
    environment:
      - NODE_ENV=development
      - MSSQL_PASSWORD=Juriti01
      - MSSQL_USER=sa
      - NPM_TOKEN=$NPM_TOKEN
    restart: always

  mssql:
    image: microsoft/mssql-server-linux:2017-GDR
    ports:
      - "1450:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Juriti01
      - MSSQL_PID=Express
      - MSSQL_COLLATION=Latin1_General_CI_AI
    restart: always

  postgres:
    image: andrglo/postgres:9.6-2
    ports:
      - 5438:5432
    restart: always


