services:

  dms:
    image: andrglo/everest:latest
    hostname: json-schema-entity
    container_name: json-schema-entity-dms-1
    command: tail -f /dev/null
    working_dir: /root/json-schema-entity
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/json-schema-entity
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - MSSQL_HOST=mssql
      - MSSQL_PASSWORD=Passw0rd
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-20.04
    container_name: json-schema-entity-mssql-1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    restart: always

  postgres:
    image: andrglo/postgres:15
    container_name: json-schema-entity-postgres-1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always


