version: '2'

services:

  dms:
    image: andrglo/everest
    hostname: json-schema-entity
    command: tail -f /dev/null
    working_dir: /andrglo/json-schema-entity
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/andrglo/json-schema-entity
    environment:
      - NODE_ENV=development
      - MSSQL_HOST=$MSSQL_HOST
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PORT=$MSSQL_PORT
      - NPM_TOKEN=$NPM_TOKEN
    restart: always

  postgres:
    image: andrglo/postgres:9.6-2
    ports:
      - 5438:5432
    restart: always


